import { StyleSheet } from "react-native";

export const mainStyle = StyleSheet.create({
  main_footer: {
    position: "static",
    bottom: 0,
  },
  h1: {
    // fontFamily: "regular",
    fontSize: 24,
    // lineHeight: "110%",
    color: "black",
    textAlign: "center",
  },
  h2: {
    // fontFamily: "regular",
    fontSize: 31,
    // lineHeight: "110%",
    color: "black",
    textAlign: "center",
    fontWeight: 600,
  },
  p_input: {
    // fontFamily: "regular",
    fontSize: 16,
    // lineHeight: "120%",
    color: "black",
    textAlign: "left",
    textAlignVertical: "center",
  },
  p_light: {
    fontWeight: 300,
    fontSize: 12,
    // lineHeight: "125%",
    textAlign: "left",
    textAlignVertical: "center",
  },
  p: {
    fontWeight: 300,
    fontSize: 16,
    // lineHeight: "125%",
    textAlign: "left",
    textAlignVertical: "center",
  },
  whiteCard: {
    backgroundColor: "white",
    height: "100%",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    flexDirection: "column",
    justifyContent: "center",
    paddingLeft: 20,
    paddingRight: 20,
  },
  inputContainer: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#A5D66D",
    borderRadius: 10,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  inputContainerFocus: {
    borderColor: "#F7B31F",
  },
  main_bloc: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "start",
    alignItems: "center",
  },
  start_bloc: {
    width: 334,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 20,
    marginTop: 20,
  },
  white_bloc: {
    backgroundColor: "white",
    width: 334,
    // height: 263,
    paddingTop: 20,
    paddingBottom: 20,
    paddingRight: 20,
    paddingRight: 20,
    flexDirection: "column",
    justifyContent: "start",
    alignItems: "center",
    borderRadius: 10,
    gap: 10,
  },
});
